version: "3.4"

services:
  chatscript:
    build:
      context: ./docker/chatscript
      dockerfile: Dockerfile
    image: chatscript
    container_name: chatscript
    ports:
      - "1024:1024"
    restart: unless-stopped
    networks:
      - alloxentric.com  # solo si usás red compartida

networks:
  alloxentric.com:
    external: true  # asegúrate de crearla con: docker network create alloxentric.com
